### ISSUE TITLE
Plans for IDP implementation handling SP Initiated SSO

### ISSUE THREAD

**Issue by JayChandler** [lightSAML/lightSAML-IDP#2]
Hello

Thx for this great work! Are there any plans to provide an IDP implementation which supports the SP Initiated SSO ? Would be nice to have.

Thx

**Comment by tmilos** [comment]
Glad to hear you like it. Give a star to the [core lightsaml lib](https://github.com/lightSAML/lightSAML)m if you don't mind, it will help it's promotion.

Well, this should be it, the IDP implementation for both SP and ISP initiated, I just don't find time these days to wrap it up and release as stable, but it's almost done. Check the profile builders from https://github.com/lightSAML/lightSAML-IDP/tree/master/src/LightSaml/Idp/Builder/Profile/WebBrowserSso/Idp and their usage for SP initiated from https://github.com/lightSAML/lightSAML-IDP/blob/master/web/idp/login.php

Also, had an idea to make and host an IDP app which will use this lib to test and prove it's usability, but still being just a hobby, again time is the biggest issue.
