### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by francislavoie** [lightSAML/lightSAML-IDP#5]
I'm trying to understand if I should be using this or just the core lib - I'm trying to implement the IdP into my project. I don't see any documentation for this lib, so it feels like I should just start from the core lib. Could you point me in the right direction?

Thanks

**Comment by tmilos** [comment]
Note that IDP has many flows and can be implemented in various ways. It's almost impossible to cover it all with one general purpose IDP lib. You can achieve everything with the [LightSAML core](https://github.com/lightSAML/lightSAML) and write your own flows. This lib just implements simple basic IDP flow with the action builders https://github.com/lightSAML/lightSAML-IDP/tree/master/src/LightSaml/Idp/Builder/Action/Profile/SingleSignOn/Idp
I'll try to write some docs on it soon.

**Comment by francislavoie** [comment]
Thanks. I ended up building my solution with the core lib. I made a couple PRs for some bugs I found there :)
